#!/usr/bin/env python

from ctypes import c_char_p, cdll, create_string_buffer
import sys
import web

libc = cdll.LoadLibrary('libdaemon.so')
rc = libc.create_participant()
if rc:
    sys.exit('creating participant failed')
libc.wait_for_historical_data()
libc.get_topics.restype = c_char_p

urls = (
    '/', 'list_urls',
    '/topic/list', 'list_topics',
)

app = web.application(urls, globals())


class list_urls:
    def GET(self):
        base = 'http://localhost:8080'
        output = 'urls:['
        output += ','.join([base + k for k in urls[2::2]])
        output += ']'
        return output


class list_topics:
    def GET(self):
        max_size = 1024 * 1024  # being generous
        s = create_string_buffer('\000' * max_size)
        rc = libc.get_topics(s, max_size)
        if rc:
            raise RuntimeError('could not get topics')

        output = 'topics:['
        output += s.value
        output += ']'
        return output


if __name__ == '__main__':
    app.run()
    print('shutting down daemon...')
    rc = libc.delete_participant()
    if rc:
        sys.exit('deleting participant failed')
